language: rust
os:
    - linux
env:
  global:
    - secure: eJG3Z3nNyv+FMPa9Vuyy20VgwF0DJaUg51Vo5KPxYBXKfIlGEvUWL2NydCSbfIeUi5L2isc9JOY74MvLP7u39A5JKg399w/EbEFssNFkTCjM34DZP886OxFHBrFqgZk77/1YUNB+Q0sozF/D9N9n+bKAN57jrJNX4ZWT5lBBm/c=
before_script:
    - rustc -v
    - cargo -V
install:
    - sudo apt-get update -qq
    - sudo apt-get install libassimp-dev
script:
    - cargo build -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
