language: rust
os:
    - linux
before_script:
    - rustc -v
    - cargo -V
install:
  - sudo apt-get update -qq
  - sudo apt-get install libassimp-dev
script:
    - cargo build -v
    - cargo doc -v
