language: rust
os:
    - linux
env:
  global:
    - secure: o+A1QB4hIMc4QjKVS7zDJ9vhCI36eXJtm1GhM64YMGRle8pvsSFktCMa0PW1+Gg+PB9DlGtmsMANMojL1KEcZQwYpzUkY030e7k9SF8kXgxOlx3hI6qNs5dAljss8whe0xCRnBT1pGWIhmZMbWAymO7YJ4nBiOYLxgr2ZJSHbhQ=
before_script:
    - rustc -v
    - cargo -V
install:
    - sudo apt-get update -qq
    - sudo apt-get install libassimp-dev
script:
    - cargo build -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
